"""Initial migration

Revision ID: 752e5c2fbef5
Revises: 
Create Date: 2025-06-15 18:40:09.250120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752e5c2fbef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='fk_admin_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='fk_bloodbank_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], name='fk_blooddrive_organizer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('last_donation', sa.DateTime(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='fk_donor_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='fk_hospital_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_bank_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_bank.id'], name='fk_bloodinventory_bloodbank_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('patient_details', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], name='fk_bloodrequest_hospital_id'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], name='fk_bloodrequest_requester_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], name='fk_driveregistration_donor_id'),
    sa.ForeignKeyConstraint(['drive_id'], ['blood_drive.id'], name='fk_driveregistration_drive_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('donation_date', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], name='fk_donation_donor_id'),
    sa.ForeignKeyConstraint(['request_id'], ['blood_request.id'], name='fk_donation_request_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_table('drive_registration')
    op.drop_table('blood_request')
    op.drop_table('blood_inventory')
    op.drop_table('hospital')
    op.drop_table('donor')
    op.drop_table('blood_drive')
    op.drop_table('blood_bank')
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
